import sqliteSource from '../sqlite/assets/tanstack-ai-schema.ts?raw'
import pgSource from '../pg/assets/tanstack-ai-schema.ts?raw'

/** Filename used by the schema emit CLI (both dialects). */
export const drizzleSchemaFilename = 'tanstack-ai-schema.ts'

/** Dialects the schema emit CLI can target. */
export type DrizzleSchemaDialect = 'sqlite' | 'pg'

/**
 * Strip the package-internal codegen banner so CLI emit produces a clean
 * user-owned module (not "do not edit by hand").
 */
function stripCodegenBanner(source: string): string {
  return source.replace(
    /^\/\*\*\n \* GENERATED by scripts\/codegen-pg-from-sqlite\.(?:ts|mjs)[\s\S]*?\*\/\n\n/,
    '',
  )
}

/**
 * Source text of the user-facing TanStack AI Drizzle schema module per
 * dialect, emitted by `tanstack-ai-drizzle-schema`. Each is structurally
 * identical to its default-schema factory (a test enforces it). The file is
 * written into the project so **their** drizzle-kit journal owns the DDL —
 * this package never ships or applies SQL migrations.
 *
 * The Postgres asset is generated from the SQLite asset
 * (`pnpm codegen:pg`); do not edit `pg/assets/` by hand.
 */
export const drizzleSchemaSources: Record<DrizzleSchemaDialect, string> = {
  sqlite: stripCodegenBanner(sqliteSource),
  pg: stripCodegenBanner(pgSource),
}

/** @deprecated Use {@link drizzleSchemaSources}.sqlite. */
export const drizzleSchemaSource: string = drizzleSchemaSources.sqlite
