import { expect, test } from '@playwright/test'

/**
 * Server-driven generation resume-snapshot persistence (`persistence: true`).
 *
 * The counterpart to `generation-persistence.spec.ts` (client-driven
 * `localStoragePersistence`). Here the hook keeps NO local store: as a run
 * streams the server records the job, and on mount / after a full
 * `page.reload()` the client hydrates the last run FROM THE SERVER via a
 * `?threadId=` GET (the `reconstructGeneration` shape). Run status + result
 * metadata survive the reload with `localStorage` empty; generated bytes are
 * never persisted, and no run is auto-started.
 *
 * Provider-free: `/api/generation-persistence-server` streams a fixed AG-UI
 * sequence and answers the hydrate GET from an in-memory job record, so there
 * is no LLM in the loop and nothing to mock (exempt from the aimock policy).
 */

test.describe('generation persistence (server-driven)', () => {
  test('records the run server-side and rehydrates it after reload with no local store', async ({
    page,
  }) => {
    await page.goto('/generation-persistence-server')
    await expect(page.getByTestId('hydration-marker')).toBeAttached()
    // Empty first load: the server has no job for this thread yet.
    await expect(page.getByTestId('snapshot-status')).toHaveText('none')

    await page.getByTestId('generate-button').click()
    await expect(page.getByTestId('snapshot-status')).toHaveText('complete')
    await expect(page.getByTestId('snapshot-result-id')).toHaveText('image-1')
    await expect(page.getByTestId('generated-image')).toHaveCount(1)

    // Server-driven mode writes NOTHING to browser storage — the record lives
    // on the server. No localStorage key mentions the generation id.
    const localKeys = await page.evaluate(() =>
      Object.keys(window.localStorage),
    )
    expect(localKeys.some((k) => k.includes('generation-server'))).toBe(false)

    // Reload with empty client storage: the snapshot is restored purely from
    // the server hydrate. Nothing auto-runs; the image (never persisted) is gone.
    await page.reload()
    await expect(page.getByTestId('hydration-marker')).toBeAttached()
    await expect(page.getByTestId('snapshot-status')).toHaveText('complete')
    await expect(page.getByTestId('snapshot-result-id')).toHaveText('image-1')
    await expect(page.getByTestId('client-status')).toHaveText('idle')
    await expect(page.getByTestId('generated-image')).toHaveCount(0)
  })
})
