import { expect, test } from '@playwright/test'

/**
 * Generation resume-snapshot persistence (browser refresh).
 *
 * Proves the story wired by `localStoragePersistence` + `useGenerateImage({
 * persistence, id })`: as a run streams, the client writes a lightweight
 * snapshot under `tanstack-ai:generation:<id>`, and a full `page.reload()`
 * hydrates it back — run status and result metadata survive, generated bytes
 * do not, and no run is auto-started.
 *
 * Provider-free: `/api/generation-persistence` streams a fixed AG-UI sequence,
 * so there is no LLM in the loop and nothing to mock (exempt from the aimock
 * policy).
 */

const STORAGE_KEY = 'tanstack-ai:generation:generation-persistence'

test.describe('generation persistence (browser refresh)', () => {
  test('persists the snapshot, hydrates it after reload, and clears it on reset', async ({
    page,
  }) => {
    await page.goto('/generation-persistence')
    await expect(page.getByTestId('hydration-marker')).toBeAttached()
    await expect(page.getByTestId('snapshot-status')).toHaveText('none')

    await page.getByTestId('generate-button').click()
    await expect(page.getByTestId('snapshot-status')).toHaveText('complete')
    await expect(page.getByTestId('snapshot-result-id')).toHaveText('image-1')
    await expect(page.getByTestId('generated-image')).toHaveCount(1)

    // The persisted record holds metadata only — never the image bytes.
    const stored = await page.evaluate(
      (key) => window.localStorage.getItem(key),
      STORAGE_KEY,
    )
    expect(stored).not.toBeNull()
    expect(stored).toContain('"status":"complete"')
    expect(stored).not.toContain('b64Json')
    expect(stored).not.toContain('iVBOR')

    // Reload: the snapshot hydrates from storage; nothing auto-runs and the
    // image itself (never persisted) is gone.
    await page.reload()
    await expect(page.getByTestId('hydration-marker')).toBeAttached()
    await expect(page.getByTestId('snapshot-status')).toHaveText('complete')
    await expect(page.getByTestId('snapshot-result-id')).toHaveText('image-1')
    await expect(page.getByTestId('client-status')).toHaveText('idle')
    await expect(page.getByTestId('generated-image')).toHaveCount(0)

    // Reset clears the in-memory snapshot and deletes the persisted record.
    await page.getByTestId('reset-button').click()
    await expect(page.getByTestId('snapshot-status')).toHaveText('none')
    await expect
      .poll(() =>
        page.evaluate((key) => window.localStorage.getItem(key), STORAGE_KEY),
      )
      .toBeNull()

    await page.reload()
    await expect(page.getByTestId('hydration-marker')).toBeAttached()
    await expect(page.getByTestId('snapshot-status')).toHaveText('none')
  })
})
