#!/usr/bin/env node
/**
 * Generate Postgres schema modules from the SQLite sources of truth.
 *
 * Source of truth:
 *   src/sqlite/default-schema.ts
 *   src/sqlite/assets/tanstack-ai-schema.ts
 *
 * Generated (do not edit by hand):
 *   src/pg/default-schema.ts
 *   src/pg/assets/tanstack-ai-schema.ts
 *
 * Usage (Node 22+ type-stripping; Node 24 recommended):
 *   node scripts/codegen-pg-from-sqlite.ts          # write
 *   node scripts/codegen-pg-from-sqlite.ts --check   # exit 1 if stale
 */
import { readFile, writeFile, mkdir } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const packageRoot = join(fileURLToPath(import.meta.url), '..', '..')

interface CodegenTarget {
  source: string
  dest: string
}

const targets: ReadonlyArray<CodegenTarget> = [
  {
    source: 'src/sqlite/default-schema.ts',
    dest: 'src/pg/default-schema.ts',
  },
  {
    source: 'src/sqlite/assets/tanstack-ai-schema.ts',
    dest: 'src/pg/assets/tanstack-ai-schema.ts',
  },
]

const GENERATED_BANNER = `/**
 * GENERATED by scripts/codegen-pg-from-sqlite.ts — do not edit by hand.
 * Source: %SOURCE%
 * Regenerate: pnpm codegen:pg
 */

`

/** Matches both current (.ts) and legacy (.mjs) codegen banners. */
const GENERATED_BANNER_RE =
  /^\/\*\*\n \* GENERATED by scripts\/codegen-pg-from-sqlite\.(?:ts|mjs)[\s\S]*?\*\/\n\n/

/**
 * Mechanical SQLite → Postgres schema projection.
 *
 * Mappings:
 *   drizzle-orm/sqlite-core → drizzle-orm/pg-core
 *   sqliteTable → pgTable
 *   text(name, { mode: 'json' }) → jsonb(name)
 *   integer(name) → bigint(name, { mode: 'number' })
 *   TanstackAiSqliteSchema / createDefaultSqliteSchema → Pg equivalents
 *   provider: 'sqlite' → provider: 'pg'
 */
export function transformSqliteSchemaToPg(
  source: string,
  { sourcePath }: { sourcePath: string },
): string {
  let out = source

  // Drop a previous generated banner if present.
  out = out.replace(GENERATED_BANNER_RE, '')

  // Strip SQLite-only "source of truth" notes from the copied docs.
  out = out
    .split('\n')
    .filter(
      (line) =>
        !line.includes('**Source of truth for the Postgres') &&
        !line.includes('`pnpm codegen:pg` to regenerate'),
    )
    .join('\n')

  // JSON text columns → jsonb (before other text/integer rewrites).
  out = out.replace(
    /text\((['"][^'"]+['"])\s*,\s*\{\s*mode:\s*['"]json['"]\s*\}\)/g,
    'jsonb($1)',
  )

  // Epoch-ms integers → bigint with number mode.
  out = out.replace(
    /integer\((['"][^'"]+['"])\)/g,
    "bigint($1, { mode: 'number' })",
  )

  out = out.replace(/\bsqliteTable\b/g, 'pgTable')
  out = out.replace(/TanstackAiSqliteSchema/g, 'TanstackAiPgSchema')
  out = out.replace(/createDefaultSqliteSchema/g, 'createDefaultPgSchema')
  out = out.replace(/provider: 'sqlite'/g, "provider: 'pg'")

  // Import block: replace sqlite-core import with pg-core imports.
  out = out.replace(
    /import\s*\{[^}]+\}\s*from\s*['"]drizzle-orm\/sqlite-core['"]/s,
    `import {
  bigint,
  index,
  jsonb,
  pgTable,
  primaryKey,
  text,
} from 'drizzle-orm/pg-core'`,
  )

  // Doc / prose adjustments.
  out = out.replace(
    /`tanstack-ai-drizzle-schema`(?! --dialect)/g,
    '`tanstack-ai-drizzle-schema --dialect pg`',
  )
  out = out.replace(
    /Default SQLite table definitions/g,
    'Default Postgres table definitions',
  )
  out = out.replace(
    /used by \{@link sqlitePersistence\} and by apps/g,
    'for apps',
  )
  out = out.replace(
    /Pass the result to \{@link drizzlePersistence\} or \{@link sqlitePersistence\},/g,
    "Pass the result to {@link drizzlePersistence} with `provider: 'pg'`,",
  )
  out = out.replace(
    /for `drizzlePersistence\(db, \{ schema \}\)` and drizzle-kit\./g,
    "for `drizzlePersistence(db, { provider: 'pg', schema })` and drizzle-kit.",
  )

  // Collapse accidental blank-line runs from filtered lines (keep max 2).
  out = out.replace(/\n{3,}/g, '\n\n')
  // Drop empty JSDoc lines left after stripping "source of truth" notes.
  out = out.replace(/\n \*\n \*\//g, '\n */')

  const banner = GENERATED_BANNER.replace('%SOURCE%', sourcePath)
  return `${banner}${out.trimStart()}`
}

function isErrnoException(error: unknown): error is NodeJS.ErrnoException {
  return error instanceof Error && 'code' in error
}

async function processTarget(
  target: CodegenTarget,
  { check }: { check: boolean },
): Promise<void> {
  const sourcePath = join(packageRoot, target.source)
  const destPath = join(packageRoot, target.dest)
  const source = await readFile(sourcePath, 'utf8')
  const generated = transformSqliteSchemaToPg(source, {
    sourcePath: target.source,
  })

  if (check) {
    let existing: string
    try {
      existing = await readFile(destPath, 'utf8')
    } catch (error) {
      if (isErrnoException(error) && error.code === 'ENOENT') {
        console.error(`Missing generated file: ${target.dest}`)
        process.exitCode = 1
        return
      }
      throw error
    }
    if (existing !== generated) {
      console.error(
        `Stale generated file: ${target.dest}\nRun: pnpm codegen:pg`,
      )
      process.exitCode = 1
      return
    }
    console.log(`ok  ${target.dest}`)
    return
  }

  await mkdir(dirname(destPath), { recursive: true })
  await writeFile(destPath, generated, 'utf8')
  console.log(`wrote ${target.dest}`)
}

const check = process.argv.includes('--check')
for (const target of targets) {
  await processTarget(target, { check })
}
if (check && process.exitCode) {
  process.exit(process.exitCode)
}
